Repository pusher/testing, pull requests merged in 2019-08, with the labels that each got.

#66 Add Kubernetes 1.14 PreSubmit to Wave
  config/jobs/wave/wave-presubmits.yaml
  images/kubebuilder-builder/Dockerfile
  images/kubebuilder-builder/Makefile
  prow/jobs.yaml
Labels: size/M

#68 Update builder images to v20190801-3bf82c1
  Makefile
  config/README.md
  config/jobs/faros/faros-postsubmits.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/git-store/git-store-presubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-postsubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-presubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-postsubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-presubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-postsubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-presubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-postsubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-presubmits.yaml
  config/jobs/quack/quack-postsubmits.yaml
  config/jobs/quack/quack-presubmits.yaml
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/wave/wave-postsubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  prow/jobs.yaml
Labels: size/M

#69 Upgrade Faros jobs to 1.14
  config/jobs/faros/faros-postsubmits.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  prow/jobs.yaml
Labels: size/L

#67 Improve Docker Build times by caching multi-stage docker builds
  images/Makefile
  images/docker-build.sh
  images/push-stages.sh
Labels: size/L

#71 Update golang-builder to go 1.12.8
  images/golang-builder/Dockerfile
Labels: size/XS

#72 Add ./configure to the k8s-spot-rescheduler postsubmit
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-postsubmits.yaml
  prow/jobs.yaml
Labels: size/XS

#73 Add python-venv to builder image
  images/python-builder/Dockerfile
Labels: size/XS

#74 Update image tags to v20190821-328974b
  Makefile
  config/README.md
  config/jobs/faros/faros-postsubmits.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/git-store/git-store-presubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-postsubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-presubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-postsubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-presubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-postsubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-presubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-postsubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-presubmits.yaml
  config/jobs/quack/quack-postsubmits.yaml
  config/jobs/quack/quack-presubmits.yaml
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/wave/wave-postsubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  prow/jobs.yaml
Labels: size/M
