Repository pusher/testing, pull requests merged in 2019-07, with the labels that each got.

#45 Simplify Python builder image
  images/Makefile
  images/admin-builder/Dockerfile
  images/builder/Dockerfile
  images/python-builder/Dockerfile
Labels: size/L

#44 [IS-326] Add Go wrapper to generate JUnit from go test output
  images/builder/runner
  images/golang-builder/Dockerfile
  images/golang-builder/wrapper/go.mod
  images/golang-builder/wrapper/go.sum
  images/golang-builder/wrapper/main.go
Labels: size/L

#46 Add Pre/Post submits for Quack
  config/jobs/quack/quack-postsubmits.yaml
  config/jobs/quack/quack-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/L

#47 Make sure to run `./configure` before building Docker image
  config/jobs/quack/quack-postsubmits.yaml
  prow/jobs.yaml
Labels: size/XS

#48 Improve test wrapper
  images/builder/runner
  images/golang-builder/Dockerfile
  images/golang-builder/wrapper/go.mod
  images/golang-builder/wrapper/go.sum
  images/golang-builder/wrapper/main.go
  images/golang-builder/wrapper/main_test.go
Labels: size/M

#49 Rotate Prow secrets
  prow/sealedsecret-hmac.yaml
  prow/sealedsecret-oauth.yaml
  prow/sealedsecret-prow-gcs.yaml
  prow/sealedsecret-quay-docker-config.yaml
  prow/sealedsecret-snyk-api-token.yaml
Labels: size/S

#50 Rotate prow-gcs secret
  prow/sealedsecret-prow-gcs.yaml
Labels: size/XS

#51 Force SSH cloning of private repositories from GitHub
  images/builder/runner
Labels: size/XS

#54 Wait for network before executing clonerefs
  images/clonerefs/Dockerfile
  images/clonerefs/clonerefs
Labels: size/S

#52 Install Docker-Compose in builder images
  images/builder/Dockerfile
Labels: size/XS

#53 Upgrade Prow deployments to apps/v1 and fix autoscaling
  prow/deck/deployment.yaml
  prow/hook/deployment.yaml
  prow/horologium/deployment.yaml
  prow/needs-rebase/deployment.yaml
  prow/plank/deployment.yaml
  prow/sinker/deployment.yaml
  prow/tide/deployment.yaml
Labels: size/L

#55 Add Golang JUnit preset
  config/README.md
  config/config.yaml
  config/jobs/git-store/git-store-presubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-presubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-presubmits.yaml
  config/jobs/quack/quack-presubmits.yaml
  prow/config.yaml
  prow/jobs.yaml
Labels: size/S

#57 Update golang-builder to go 1.12.7
  images/README.md
  images/golang-builder/Dockerfile
Labels: size/XS

#56 Update Builder images to v20190716 842415b
  Makefile
  config/README.md
  config/config.yaml
  config/jobs/faros/faros-postsubmits.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/git-store/git-store-presubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-postsubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-presubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-postsubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-presubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-postsubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-presubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-postsubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-presubmits.yaml
  config/jobs/quack/quack-postsubmits.yaml
  config/jobs/quack/quack-presubmits.yaml
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/wave/wave-postsubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  prow/config.yaml
  prow/jobs.yaml
Labels: size/M

#59 Revert clonerefs to previous known working version
  config/config.yaml
  prow/config.yaml
Labels: size/XS

#58 Extend branches istio builds against
  config/jobs/istio/istio.pusher-release.yaml
  prow/jobs.yaml
Labels: size/XS

#61 Use nslookup to check network connectivity
  images/clonerefs/clonerefs
Labels: size/XS

#64 Enable Deck Rerun button
  config/config.yaml
  prow/config.yaml
  prow/deck/deployment.yaml
  prow/deck/role.yaml
  prow/hook/deployment.yaml
  prow/horologium/deployment.yaml
  prow/needs-rebase/deployment.yaml
  prow/plank/deployment.yaml
  prow/sealedsecret-cookie-secret.yaml
  prow/sealedsecret-github-oauth-config.yaml
  prow/sinker/deployment.yaml
  prow/tide/deployment.yaml
Labels: size/L

#63 Minor fixups to `builder` image
  images/builder/Dockerfile
  images/builder/runner
Labels: size/XS

#60 Add Docker Builder pipeline for testing repo
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  images/Makefile
  images/README.md
  prow/jobs.yaml
  prow/pipeline/clusterrole.yaml
  prow/pipeline/crb.yaml
  prow/pipeline/deployment.yaml
  prow/pipeline/serviceaccount.yaml
  tekton/pipelines/testing/post-builder-images.yaml
  tekton/pipelines/testing/pull-builder-images.yaml
  tekton/pipelines/testing/task-testing-pull-build-image.yaml
Labels: size/L

#65 Update builder images to v20190730-3bc1149
  Makefile
  config/README.md
  config/jobs/faros/faros-postsubmits.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/git-store/git-store-presubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-postsubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-presubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-postsubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-presubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-postsubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-presubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-postsubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-presubmits.yaml
  config/jobs/quack/quack-postsubmits.yaml
  config/jobs/quack/quack-presubmits.yaml
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/wave/wave-postsubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  prow/jobs.yaml
Labels: size/M
