Repository pusher/testing, pull requests merged in 2019-04, with the labels that each got.

#4 Remove superfluous push-latest
  config/jobs/testing/testing-postsubmits.yaml
  prow/jobs.yaml
Labels: size/XS

#3 Pin images to :v20190401-6a7e3ff
  config/config.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/testing/testing-postsubmits.yaml
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  prow/config.yaml
  prow/jobs.yaml
Labels: size/M

#5 Add multi K8s version tests for Faros
  config/jobs/faros/faros-presubmits.yaml
  prow/jobs.yaml
Labels: size/L

#7 Move arg flattening before -o xtrace
  images/builder/runner
Labels: size/XS

#8 Add Istio config to jobs
  config/config.yaml
  config/jobs/istio/istio.pusher-release.yaml
  config/plugins.yaml
  prow/config.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/XL

#9 Config rework
  config/jobs/faros/faros-postsubmits.yaml
  config/jobs/faros/faros-presubmits.yaml
  config/jobs/wave/wave-postsubmits.yaml
  config/jobs/wave/wave-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/XL

#10 Check whether gcloud exists or not
  images/builder/runner
Labels: size/XS

#11 Prom rule reloader
  config/jobs/prom-rule-reloader/prom-rule-reloader-postsubmits.yaml
  config/jobs/prom-rule-reloader/prom-rule-reloader-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/L

#6 Update components, add liveness and readiness probes
  config/config.yaml
  prow/config.yaml
  prow/deck/deployment.yaml
  prow/deck/hpa.yaml
  prow/deck/pdb.yaml
  prow/hook/deployment.yaml
  prow/hook/hpa.yaml
  prow/hook/pdb.yaml
  prow/horologium/deployment.yaml
  prow/plank/deployment.yaml
  prow/sinker/deployment.yaml
  prow/tide/deployment.yaml
Labels: size/L

#13 Fix logo path in config
  config/config.yaml
  prow/config.yaml
Labels: size/XS

#12 Add initial documentation
  README.md
  config/README.md
  config/jobs/README.md
  images/README.md
Labels: size/L

#14 Fix favicon path
  config/config.yaml
  prow/config.yaml
Labels: size/XS

#16 Add Pre/PostSubmits for K8s-Spot-Rescheduler
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-postsubmits.yaml
  config/jobs/k8s-spot-rescheduler/k8s-spot-rescheduler-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/L

#15 Add Pre/PostSubmits for Git-Store
  config/jobs/git-store/git-store-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/M

#18 Add k8s-spot-price-monitor Pre/Postsubmits
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-postsubmits.yaml
  config/jobs/k8s-spot-price-monitor/k8s-spot-price-monitor-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/L

#19 Add Pre/Postsubmits for k8s-spot-termination-handler
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-postsubmits.yaml
  config/jobs/k8s-spot-termination-handler/k8s-spot-termination-handler-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/L

#17 Add Python based builder image
  images/Makefile
  images/README.md
  images/python-builder/Dockerfile
Labels: size/L
