Repository pusher/testing, pull requests merged in 2020-01, with the labels that each got.

#88 Attempt to fix Prow checks
  Makefile
  images/docker-build.sh
  images/kubebuilder-builder/Makefile
  prow/deck/deployment.yaml
  prow/hook/deployment.yaml
  prow/horologium/deployment.yaml
  prow/plank/deployment.yaml
  prow/sinker/deployment.yaml
  prow/tide/deployment.yaml
  scripts/check-image-tags.sh
Labels: size/S

#86 Upgrade Golang to 1.13 in builder image
  images/golang-builder/Dockerfile
Labels: size/S

#89 Update golangci-lint to support go 1.13
  images/README.md
  images/golang-builder/Dockerfile
Labels: size/XS

#90 elasticsearch
  Makefile
  config/jobs/elasticsearch-docker/elasticsearch-docker-postsubmits.yaml
  config/jobs/elasticsearch-docker/elasticsearch-docker-presubmits.yaml
  config/plugins.yaml
  prow/jobs.yaml
  prow/plugins.yaml
Labels: size/L

#92 Add ruby-builder image based on Debian Stretch
  images/Makefile
  images/README.md
  images/ruby-builder/Dockerfile
Labels: size/L
