Repository pusher/testing, pull requests merged in 2020-03, with the labels that each got.

#87 Update Prow components to v20191219-ecbeba384
  config/config.yaml
  config/jobs/istio/istio.pusher-release-1.2.yaml
  prow/config.yaml
  prow/deck/deployment.yaml
  prow/deck/role.yaml
  prow/hook/deployment.yaml
  prow/hook/role.yaml
  prow/horologium/deployment.yaml
  prow/jobs.yaml
  prow/needs-rebase/deployment.yaml
  prow/plank/deployment.yaml
  prow/plank/role.yaml
  prow/sinker/deployment.yaml
  prow/sinker/role.yaml
  prow/tide/deployment.yaml
  prow/tide/role.yaml
Labels: lgtm, size/M

#94 Turn on faros
  config/plugins.yaml
  prow/plugins.yaml
Labels: size/XS

#95 Autoupdate periodic
  Makefile
  config/jobs/testing/testing-presubmits.yaml
  config/jobs/testing/testing-update-prow-periodic.yaml
  prow/jobs.yaml
Labels: size/L

#99 Bump prow from v20191219-ecbeba384 to v20200302-c921a880e
  prow/deck/deployment.yaml
  prow/hook/deployment.yaml
  prow/horologium/deployment.yaml
  prow/needs-rebase/deployment.yaml
  prow/plank/deployment.yaml
  prow/sinker/deployment.yaml
  prow/tide/deployment.yaml
Labels: lgtm, size/S

#100 [IS-1012] - Update config for new prow version
  config/config.yaml
  config/plugins.yaml
  prow/config.yaml
  prow/plugins.yaml
Labels: size/M

#101 Bump prow from v20200302-c921a880e to v20200305-e8ef9758b
  prow/deck/deployment.yaml
  prow/hook/deployment.yaml
  prow/horologium/deployment.yaml
  prow/needs-rebase/deployment.yaml
  prow/plank/deployment.yaml
  prow/sinker/deployment.yaml
  prow/tide/deployment.yaml
Labels: size/S

#102 [IS-1010] - Add scripts to update utility images
  Makefile
  scripts/preflight_checks.sh
  scripts/update_prow_components.sh
Labels: size/M

#103 [IS-1014] - Update utility images
  Makefile
  config/config.yaml
  prow/config.yaml
Labels: size/S

#105 Update rerun_auth_config
  config/config.yaml
  prow/config.yaml
Labels: size/S
